name: CI Workflow

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64, armv7]
        include:
          - platform: amd64
            arch: amd64
          - platform: arm64
            arch: arm64
          - platform: armv7
            arch: arm/v7
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.arch }}
          context: .
          push: false
          load: true
          tags: xiaomusic:ci-${{ matrix.platform }}
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}

      - name: Test Docker image for ${{ matrix.platform }}
        run: |
          docker run --rm xiaomusic:ci-${{ matrix.platform }} /app/.venv/bin/python3 /app/xiaomusic.py -h
